#!/bin/bash

# Comandos
case "$1" in
	build ) echo "Instalando..."
  	docker compose -f docker-compose.yml build
    # docker compose -f docker-compose.yml run frontend ./install.sh
    # docker compose -f docker-compose.yml
    ;;
  up ) echo "Iniciando servidores.."
    docker compose -f docker-compose.yml up -d
    ;;
  down ) echo "Deteniendo servidores.."
    docker compose -f docker-compose.yml down
    ;;
	restart ) echo "Reiniciando servicio $2..."
		docker compose -f docker-compose.yml restart $2
		;;
	restart-all ) echo "Reiniciando servidores.."
		docker compose -f docker-compose.yml restart
		;;
	log ) docker compose -f docker-compose.yml logs -f $2
		;;
	logs ) docker compose -f docker-compose.yml logs -f
		;;
  sh ) echo "Conectando con $2"
    docker exec -it $2 sh
    ;;
  mvn ) echo "Ejecutando Maven en servidor backend: $2"
    docker exec -t backend mvn $2
    ;;
  test ) echo "Testing"
    docker compose run -t --rm testing
    ;;
  staging ) echo "Cargando staging $2"
    cat ./staging/$2.sql | docker exec -i database psql -q -U ${POSTGRES_USER:-resctpet_admin} -d ${POSTGRES_DB:-resctpet_db}
    ;;
  * ) echo "Opción inválida."
      ;;
esac
