
# database
spring.datasource.url=jdbc:postgresql://database:5432/${POSTGRES_DB:resctpet_db}
spring.datasource.username=${POSTGRES_USER:resctpet_admin}
spring.datasource.password=${POSTGRES_PASSWORD:R3sctP3t_S3cur3_P@ssw0rd_2026!}
spring.jpa.hibernate.ddl-auto=update

# devtools
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s